# Generated by Django 3.2.1 on 2021-11-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=20, verbose_name='Name'),
        ),
    ]
